
-- Generated by scripts/generate-units.mjs. DO NOT EDIT!

Program {
    Name = "cmd_dx12",
    Depends = {
        "d3d12"
    },
    Sources = {
        "src/cmd_dx12/main.cc"
    }
}

Program {
    Name = "cmd_game",
    Depends = {
        "d3d12",
        "ecs",
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "components",
        "math",
        "imgui"
    },
    Sources = {
        "src/cmd_game/game.cc",
        "src/cmd_game/main.cc"
    }
}

Program {
    Name = "cmd_game2",
    Depends = {
        "components",
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "math",
        "ecs",
        "imgui",
        "renderer-dx12",
        "d3d12",
        "loader",
        "png",
        "zlib"
    },
    Sources = {
        "src/cmd_game2/box-rendering-system.cc",
        "src/cmd_game2/main.cc"
    }
}

Program {
    Name = "cmd_vdv",
    Depends = {
        "renderer-dx12",
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "d3d12",
        "imgui",
        "loader",
        "png",
        "zlib",
        "math"
    },
    Sources = {
        "src/cmd_vdv/main.cc"
    }
}

StaticLibrary {
    Name = "common",
    Depends = {
        { "windows"; Config = "win64-*-*" },
        "xxhash"
    },
    Sources = {
        "src/common/cli.cc",
        "src/common/mem.cc",
        { "src/common/file_windows.cc"; Config = "win64-*-*" }
    }
}

Program {
    Name = "common_cli_test",
    Depends = {
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "common",
        "test"
    },
    Sources = {
        "src/common/cli_test.cc"
    }
}

Program {
    Name = "common_file_test",
    Depends = {
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "common",
        "test"
    },
    Sources = {
        "src/common/file_test.cc"
    }
}

Program {
    Name = "common_hash_map_test",
    Depends = {
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "common",
        "test"
    },
    Sources = {
        "src/common/hash_map_test.cc"
    }
}

Program {
    Name = "common_hash_test",
    Depends = {
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "common",
        "test"
    },
    Sources = {
        "src/common/hash_test.cc"
    }
}

Program {
    Name = "common_list_test",
    Depends = {
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "common",
        "test"
    },
    Sources = {
        "src/common/list_test.cc"
    }
}

Program {
    Name = "common_mem_test",
    Depends = {
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "common",
        "test"
    },
    Sources = {
        "src/common/mem_test.cc"
    }
}

StaticLibrary {
    Name = "components",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "math"
    },
    Sources = {
        "src/components/components.cc"
    }
}

StaticLibrary {
    Name = "ecs",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "components",
        "math"
    },
    Sources = {
        "src/ecs/archetype.cc",
        "src/ecs/chunk.cc",
        "src/ecs/entity-manager.cc",
        "src/ecs/entity-query.cc",
        "src/ecs/local-to-world-system.cc",
        "src/ecs/world.cc"
    }
}

Program {
    Name = "ecs_archetype_test",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "components",
        "math",
        "ecs",
        "test"
    },
    Sources = {
        "src/ecs/archetype_test.cc"
    }
}

Program {
    Name = "ecs_chunk_test",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "components",
        "math",
        "ecs",
        "test"
    },
    Sources = {
        "src/ecs/chunk_test.cc"
    }
}

Program {
    Name = "ecs_component-registry_test",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "components",
        "math",
        "ecs",
        "test"
    },
    Sources = {
        "src/ecs/component-registry_test.cc"
    }
}

Program {
    Name = "ecs_components_test",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "components",
        "math",
        "ecs",
        "test"
    },
    Sources = {
        "src/ecs/components_test.cc"
    }
}

Program {
    Name = "ecs_entity-manager_test",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "components",
        "math",
        "ecs",
        "test"
    },
    Sources = {
        "src/ecs/entity-manager_test.cc"
    }
}

Program {
    Name = "ecs_entity-query_test",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "components",
        "math",
        "ecs",
        "test"
    },
    Sources = {
        "src/ecs/entity-query_test.cc"
    }
}

Program {
    Name = "ecs_local-to-world-system_test",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "components",
        "math",
        "ecs",
        "test"
    },
    Sources = {
        "src/ecs/local-to-world-system_test.cc"
    }
}

StaticLibrary {
    Name = "loader",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "png",
        "zlib"
    },
    Sources = {
        "src/loader/tex-loader.cc"
    }
}

Program {
    Name = "loader_tex-loader_test",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "png",
        "zlib",
        "loader",
        "test"
    },
    Sources = {
        "src/loader/tex-loader_test.cc"
    }
}

StaticLibrary {
    Name = "math",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash"
    },
    Sources = {
        "src/math/data.cc"
    }
}

Program {
    Name = "math_data_test",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "math",
        "test"
    },
    Sources = {
        "src/math/data_test.cc"
    }
}

Program {
    Name = "math_mat4_test",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "math",
        "test"
    },
    Sources = {
        "src/math/mat4_test.cc"
    }
}

Program {
    Name = "math_transform_test",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "math",
        "test"
    },
    Sources = {
        "src/math/transform_test.cc"
    }
}

Program {
    Name = "math_vec3_test",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "math",
        "test"
    },
    Sources = {
        "src/math/vec3_test.cc"
    }
}

StaticLibrary {
    Name = "renderer-dx12",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "d3d12",
        "imgui",
        "loader",
        "png",
        "zlib",
        "math"
    },
    Sources = {
        { "src/renderer-dx12/renderer_windows.cc"; Config = "win64-*-*" },
        { "src/renderer-dx12/wnd-proc_windows.cc"; Config = "win64-*-*" }
    }
}

Program {
    Name = "renderer-dx12_renderer_test",
    Depends = {
        "common",
        { "windows"; Config = "win64-*-*" },
        "xxhash",
        "d3d12",
        "imgui",
        "loader",
        "png",
        "zlib",
        "math",
        "renderer-dx12",
        "test"
    },
    Sources = {
        "src/renderer-dx12/renderer_test.cc"
    }
}

StaticLibrary {
    Name = "test",
    Depends = {
        { "windows"; Config = "win64-*-*" }
    },
    Sources = {
        "src/test/test.c"
    }
}

