#include "components.hh"

// Generated by generate-components.mjs. DO NOT EDIT!

using namespace game;

Slice<const TypeInfo> game::GetComponentTypeInfoArray() {
  static const TypeInfo components[] = {
    GAME_COMPONENT(Entity),
    GAME_COMPONENT(LocalToWorld),
    GAME_COMPONENT(Rotation),
    GAME_COMPONENT(Scale),
    GAME_COMPONENT(Translation),
  };
  return slice::FromArray(components);
}
