#pragma once

// Generated by generate-components.mjs. DO NOT EDIT!

#include "../ecs/type-system.hh"

namespace game {
struct LocalToWorld {
  enum { COMPONENT_TYPE = 1 };

  mat4 value_;
};

struct Rotation {
  enum { COMPONENT_TYPE = 2 };

  quat value_;
};

struct Scale {
  enum { COMPONENT_TYPE = 3 };

  f32 value_;
};

struct Translation {
  enum { COMPONENT_TYPE = 4 };

  vec3 value_;
};

Slice<const TypeInfo> GetComponentTypeInfoArray();
} // namespace game
